package es.ua.dlsi.im3.analysis.analysis.analyzers.tonal.academic.melodic;

/**
 * All used features
 * @author drizo
 *
 */
public enum MelodicFeatures {
    PREV_INTERVAL_NAME, PREV_INTERVAL_DIR, PREV_INTERVAL_MODE, 
    NEXT_INTERVAL_NAME, NEXT_INTERVAL_MODE,  NEXT_INTERVAL_DIR, 
    TIED_FROM_PREVIOUS,
    RATIO, 
    METER_NUMERATOR, 
    INSTABILITY, 
    NEXT_INSTABILITY,
    BELONGS_TO_CHORD, //BELONGS_TO_KEY, 
    PREVIOUS_NOTE_TAG, NEXT_NOTE_TAG,
    PREV_BELONGS_TO_CHORD, NEXT_BELONGS_TO_CHORD,
    EXPECTED_ANALYSIS,
    MIDI_NOTE // used for debug
   
	/*PREV_INTERVAL, NEXT_INTERVAL, BEAT, 
	BEAT_OFFSET, DURATION, 
	CHROMATISM, NEXT_CHROMATISM, PITCH_DISTANCE, NEXT_PITCH_DISTANCE,
	STRONG, 
	BEAT_FLOAT, NEXT_DURATION, PREV_DURATION, WAITING_FOR_HARMONY,  , QUARTER_PART,
	INSTABILITY_RATIO, PREV_INTERVAL_SEMITONES, NEXT_INTERVAL_SEMITONES,
	// used for the classifier with harmony	
	//ONSET_IN_TIME,
	
	,
	// new features after Placido's PhD 2016
	*/
	
}
